SELECT * FROM Customers;


-- WHERE Command

SELECT * FROM Customers
WHERE CITY='ÝSTANBUL'

-- ctrl+t yapýp çalýþtýrýnca gridleri kapatýp sonuç verir(text halinde )
-- eski haline dönmesi için ctrl+d yapmamýz lazým 
-- ctrl+shift+f dosya halinde kaydeder

SELECT * FROM Customers
WHERE CITY <> 'ÝZMÝR';

SELECT * FROM Customers
WHERE not CITY = 'ÝZMÝR'; -- Eþit deðildirle aynýdýr.

SELECT * FROM Customers
WHERE BIRTHDATE > '19971024'; 
--Dilden baðýmsýz çalýþabilen sorunsuz bir tarih formatýdýr.YýlAyGün

SELECT * FROM Customers
WHERE BIRTHDATE BETWEEN '19971024' and '19991024';


UPDATE Customers SET AGE = DATEDIFF(YEAR, BIRTHDATE, GETDATE());

SELECT * FROM Customers
WHERE AGE BETWEEN 24 AND 32

UPDATE Customers SET AGE = DATEDIFF(MONTH, BIRTHDATE, GETDATE());

ALTER TABLE CUSTOMERS
ADD AGE_MONTH VARCHAR(10);

UPDATE Customers SET AGE_MONTH = DATEDIFF(MONTH, BIRTHDATE, GETDATE());


/* Regex */

--Ali ile baþlayanlar
SELECT * FROM Customers
WHERE CUSTOMERNAME LIKE 'ALÝ%'  


--Ali ile baþlamayanlar
SELECT * FROM Customers
WHERE CUSTOMERNAME not LIKE 'ALÝ%'


--Ad ve soyadýn içerisinde Alp ile bitenler
SELECT * FROM Customers
WHERE CUSTOMERNAME LIKE '%ALP'


--ismi Alp ile bitmeyenler
SELECT * FROM Customers
WHERE CUSTOMERNAME not LIKE '%ALP'

--ismin içerisinde AL geçenler.
SELECT * FROM Customers
WHERE CUSTOMERNAME LIKE '%AL%'


SELECT * FROM Customers
WHERE CITY IN('ÝSTANBUL')

SELECT * FROM Customers
WHERE CITY IN('ÝSTANBUL','ANKARA')

SELECT * FROM Customers
WHERE CITY IN('ÝSTANBUL','ANKARA','ÝZMÝR')



SELECT COUNT(*) FROM Customers
WHERE CUSTOMERNAME LIKE '%ER%';

SELECT * FROM Customers
WHERE CITY IN ('ÝSTANBUL', 'ÝZMÝR' );


UPDATE Customers SET GENDER = 'E' WHERE GENDER = 'ERKEK'
UPDATE Customers SET GENDER = 'K' WHERE GENDER = 'KADIN'

UPDATE Customers SET GENDER = 'ERKEK' WHERE GENDER = 'E'
UPDATE Customers SET GENDER = 'KADIN' WHERE GENDER = 'K'


-- DELETE Customers WHERE ID IN (18,19,90)


-- AND --- OR OPERATORS

SELECT * FROM Customers
WHERE CITY = 'ÝSTANBUL' AND DISTRICT = 'ESENLER' AND GENDER='KADIN' 


SELECT * FROM Customers
WHERE CITY = 'ÝSTANBUL' AND BIRTHDATE BETWEEN '19900102' AND '20000203' AND GENDER='KADIN' 


SELECT * FROM CUSTOMERS
WHERE CITY = 'ÝSTANBUL' OR CITY='ÝZMÝR' ;

SELECT * FROM CUSTOMERS
WHERE CITY IN ('ÝSTANBUL', 'ÝZMÝR');

SELECT * FROM CUSTOMERS
WHERE CITY NOT IN ('ÝSTANBUL', 'ÝZMÝR');

SELECT * FROM CUSTOMERS
WHERE CITY LIKE ('Ý%');

SELECT * FROM CUSTOMERS
WHERE CITY LIKE 'Ý%' OR CITY LIKE '%K'


SELECT * FROM CUSTOMERS
WHERE CITY LIKE 'Ý%%R' 


--DISTINCT KOMUTU
--Türkiyenin hangi illerinden müþterimiz var?
SELECT DISTINCT CITY
FROM Customers
--Toplamda istanbul da kaç tane ilçe vardýr?
SELECT CITY,DISTRICT FROM Customers
WHERE CITY='ÝSTANBUL'

SELECT DISTINCT CITY,DISTRICT FROM Customers
WHERE CITY='ÝSTANBUL'

SELECT DISTINCT CITY,DISTRICT FROM Customers
WHERE CITY IN ('ÝSTANBUL','ANKARA')

SELECT DISTINCT GENDER FROM CUSTOMERS 
WHERE CITY='ÝSTANBUL'

SELECT DISTINCT CITY,GENDER FROM CUSTOMERS 
WHERE CITY IN ('ÝSTANBUL','ANKARA')

--Müþteriler hangi yaþlarda
--Ýstanbul daki müþterilerin yaþý
SELECT DISTINCT AGE FROM CUSTOMERS 
WHERE CITY='ÝSTANBUL'

SELECT DISTINCT AGE,GENDER FROM CUSTOMERS 
WHERE CITY IN ('ÝSTANBUL','ANKARA')

SELECT DISTINCT GENDER,AGE FROM CUSTOMERS 
WHERE CITY IN ('ÝSTANBUL','ANKARA')

SELECT DISTINCT customername,GENDER,AGE FROM CUSTOMERS 
WHERE CITY IN ('ÝSTANBUL','ANKARA')

SELECT DISTINCT AGE,customername,GENDER FROM CUSTOMERS 
WHERE CITY IN ('ÝSTANBUL','ANKARA')

--ORDER BY KOMUTU
SELECT * FROM Customers
order by ýd

SELECT * FROM Customers
ORDER BY CUSTOMERNAME DESC

SELECT * FROM Customers
ORDER BY BIRTHDATE DESC

SELECT * FROM Customers
ORDER BY CITY
--ÝKÝ KOLONA GÖRE SIRALAMA
SELECT * FROM Customers
ORDER BY CITY,CUSTOMERNAME

SELECT * FROM Customers
ORDER BY CITY,CUSTOMERNAME DESC

SELECT * FROM Customers
ORDER BY CITY,DISTRICT,CUSTOMERNAME

SELECT * FROM Customers
WHERE CITY='ÝSTANBUL'
ORDER BY CITY,DISTRICT,CUSTOMERNAME

SELECT * FROM Customers
WHERE CITY='ÝSTANBUL'
ORDER BY 1

SELECT * FROM Customers
WHERE CITY='ÝSTANBUL'
ORDER BY 2 --CUSTOMERNAME KOLONUNA GÖRE SIRALADI.

SELECT * FROM Customers
WHERE CITY='ÝSTANBUL'
ORDER BY 5,2,1 --DISTRICT,CUSTOMERNAME,ID

SELECT * FROM Customers
WHERE CITY='ÝSTANBUL'
ORDER BY AGE ASC

SELECT * FROM Customers
WHERE CITY='ÝSTANBUL'
ORDER BY AGE DESC


--TOP KOMUTU
SELECT * FROM Customers

SELECT TOP 100 * FROM Customers

SELECT TOP 200 * FROM Customers

SELECT TOP 10 * FROM Customers

SELECT TOP 10 PERCENT * FROM Customers

SELECT TOP 50 PERCENT * FROM Customers